### ISSUE TITLE
Symfony 6 support release

### ISSUE THREAD

**Issue by barell** [infection/codeception-adapter#13]
Hello, do you plan any release soon to support Symfony 6? Or is it related to codeception v5 release?

**Comment by maks-rafalko** [comment]
Hello, just released PHP 8.1 and Symfony 6 support https://github.com/infection/codeception-adapter/releases/tag/0.4.1

Please, let us know if it does not work.

**Comment by barell** [comment]
unfortunately I can't test it yet, because codeception symfony itself does not support symfony 6 yet https://github.com/Codeception/module-symfony/issues/152

once this is ready i will come back
