### ISSUE TITLE
Problem with running Infection

### ISSUE THREAD

**Issue by Apcenuu** [infection/codeception-adapter#20]
I trying to use Infection with Codeception tests in my project, and run vendor/bin/infection failed with error:

`[ERROR] Project tests must be in a passing state before running Infection.                                             
         Check the executed command to identify the problem: '/Users/arseniy/projects/project1/vendor/bin/codecept'    
         'run' '--no-colors' '--fail-fast' '--coverage-phpunit' 'codeception-coverage-xml' '--xml'                      
         '/Users/arseniy/projects/project1/tests/_output/infection/junit.xml' '-o' 'paths: output:                     
         /Users/arseniy/projects/project1/tests/_output/infection' '-o' 'coverage: enabled: true' '-o' 'coverage:      
         include: [src/*]' '-o' 'settings: shuffle: true'                                                               
         codeception reported an exit code of 143.                                                                      
         Refer to the codeception's output below:                                                                       
         STDOUT:                                                                                                        
         Codeception PHP Testing Framework v5.0.11 https://helpukrainewin.org`

After I trying run this command directly, and this works OK, Codeception tests passed, I see coverage report in console.  

`'vendor/bin/codecept' 'run' '--no-colors' '--fail-fast' '--coverage-phpunit' 'codeception-coverage-xml' '--xml' '/Users/arseniy/projects/project1/tests/_output/infection/junit.xml' '-o' 'paths: output: /Users/arseniy/projects/project1/tests/_output/infection' '-o' 'coverage: enabled: true' '-o' 'coverage: include: [src/*]' '-o' 'settings: shuffle: true'`

But Infection cant run this command.

My infection.json5 config is:

```json
{
    "$schema": "vendor/infection/infection/resources/schema.json",
    "tmpDir": "tests/_output",
    "testFramework": "codeception",
    "source": {
        "directories": [
            "src"
        ],
        "excludes": [
            "DataFixtures",
            "Form",
            "Kernel.php"
        ]
    },
    "mutators": {
        "@default": true
    }
}

**Comment by sidz** [comment]
Hey @Apcenuu.

Any chance you could share a link to public repository?

**Comment by Apcenuu** [comment]
https://github.com/Apcenuu/test-form/tree/infection

**Comment by sidz** [comment]
![image](https://github.com/infection/codeception-adapter/assets/1302230/14a2c285-cdf5-4181-9c9a-e609395ae8b1)
**FormCest: Validation test** is failed.

**Comment by Apcenuu** [comment]
You run ```bin/console doctrine:fixtures:load?``` Validation test requires it.

<img width="775" alt="Снимок экрана 2023-10-15 в 16 18 03" src="https://github.com/infection/codeception-adapter/assets/62610873/95d7312b-22ef-4013-ac78-be92bda39261">

I have same error with ```codecoverage.serialized``` file, but manual creating this file solves this trouble.
After this, tests run in my container:

<img width="1389" alt="Снимок экрана 2023-10-15 в 16 17 42" src="https://github.com/infection/codeception-adapter/assets/62610873/570b65a6-542f-42d1-8521-c0eaf5375154">

**Comment by Apcenuu** [comment]
I was able to run the infection tests, but ```codecoverage.serialized``` file cannot be created on its own. I need create him manually before every infection run

**Comment by sidz** [comment]
Initially I assumed that you have an issue with Infection but `Code coverage file /app/tests/_output/infection/c3tmp/codecoverage.serialized does not exist` is not related to Infection.

It's Codeception issue.

Documentation: https://codeception.com/docs/Codecoverage#remote-codecoverage

Related Issues in Codeception:
- https://github.com/Codeception/Codeception/issues/6583
- https://github.com/Codeception/Codeception/issues/6533
- https://github.com/Codeception/Codeception/issues/6519
